### ISSUE TITLE
When trying to build the project on linux, I am getting the error that " cuda_runtime.h" is not found 

### ISSUE THREAD

**Issue by lokitkhemka** [RaymondMcGuire/sph_seepage_flows#2]
I am getting the error 
```
./sph_seepage_flows/seepage_flows_cuda/include/kiri_pbs_cuda/cuda_helper/helper_math.h:44:10: fatal error: cuda_runtime.h: No such file or directory
```

However, the `cuda_runtime.h` file is available in the folder `/usr/local/cuda/include`. How can I include this into the project?

Thank you.

**Comment by RaymondMcGuire** [comment]
> I am getting the error
> 
> ```
> ./sph_seepage_flows/seepage_flows_cuda/include/kiri_pbs_cuda/cuda_helper/helper_math.h:44:10: fatal error: cuda_runtime.h: No such file or directory
> ```
> 
> However, the `cuda_runtime.h` file is available in the folder `/usr/local/cuda/include`. How can I include this into the project?
> 
> Thank you.

This code has only been tested on Windows. If you're using Linux or macOS, it may not work correctly.

**Comment by lokitkhemka** [comment]
Hi, it was working fine on windows. Thank you.
