### ISSUE TITLE
Recreating a example 4 from preprint

### ISSUE THREAD

**Issue by lokitkhemka** [RaymondMcGuire/sph_seepage_flows#3]
I want to recreate Example 4 from the paper preprint. But, the required files are not present in the repo. Can you add that, if possible? It will be of great help to me.

Thank you.

**Comment by RaymondMcGuire** [comment]
I'm very sorry I forgot to reply to your question earlier. You can find similar examples under the blender branch of this project.

https://github.com/RaymondMcGuire/sph_seepage_flows/tree/blender
